CREATE TABLE public.customer_snapshot (
	customer_id varchar NOT NULL,
	days_since_first_order int4 NULL,
	days_since_last_order int4 NULL,
	is_newsletter_subscriber bool NULL,
	orders int4 DEFAULT 0 NOT NULL,
	items int4 DEFAULT 0 NOT NULL,
	cancels int4 DEFAULT 0 NOT NULL,
	"returns" int4 DEFAULT 0 NOT NULL,
	different_addresses int4 DEFAULT 0 NOT NULL,
	shipping_addresses int4 DEFAULT 0 NOT NULL,
	devices int4 DEFAULT 0 NOT NULL,
	vouchers int4 DEFAULT 0 NOT NULL,
	cc_payments int4 DEFAULT 0 NOT NULL,
	paypal_payments int4 DEFAULT 0 NOT NULL,
	afterpay_payments int4 DEFAULT 0 NOT NULL,
	apple_payments int4 DEFAULT 0 NOT NULL,
	female_items int4 DEFAULT 0 NOT NULL,
	male_items int4 DEFAULT 0 NOT NULL,
	unisex_items int4 DEFAULT 0 NOT NULL,
	wapp_items int4 DEFAULT 0 NOT NULL,
	wftw_items int4 DEFAULT 0 NOT NULL,
	mapp_items int4 DEFAULT 0 NOT NULL,
	wacc_items int4 DEFAULT 0 NOT NULL,
	macc_items int4 DEFAULT 0 NOT NULL,
	mftw_items int4 DEFAULT 0 NOT NULL,
	wspt_items int4 DEFAULT 0 NOT NULL,
	mspt_items int4 DEFAULT 0 NOT NULL,
	curvy_items int4 DEFAULT 0 NOT NULL,
	sacc_items int4 DEFAULT 0 NOT NULL,
	msite_orders int4 DEFAULT 0 NOT NULL,
	desktop_orders int4 DEFAULT 0 NOT NULL,
	android_orders int4 DEFAULT 0 NOT NULL,
	ios_orders int4 DEFAULT 0 NOT NULL,
	other_device_orders int4 DEFAULT 0 NOT NULL,
	work_orders int4 DEFAULT 0 NOT NULL,
	home_orders int4 DEFAULT 0 NOT NULL,
	parcelpoint_orders int4 DEFAULT 0 NOT NULL,
	other_collection_orders int4 DEFAULT 0 NOT NULL,
	average_discount_onoffer float8 NULL,
	average_discount_used float8 NULL,
	coupon_discount_applied float8 NULL,
	redpen_discount_used float8 NULL,
	revenue float8 NULL,
	CONSTRAINT customer_snapshot_pkey PRIMARY KEY (customer_id)
);